# Site
title:              'Tu Mai Anh Do'
bio:                'Ph.D. Candidate in Computer Science, USC'
description:        "Tu Mai Anh Do is a Ph.D. Candidate at the University of Southern Californa"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/avatar.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://tumaianhdo.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         tumaianhdo.github.io/_sass
  style:            compressed

# Comments
disqus_shortname:   tumaianhdo

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              tudo@isi.edu
# twitter:            username
facebook:           tumaianhdo
github-url:         tumaianhdo
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           tumaianhdo
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
